# Generated by Django 5.0 on 2024-05-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kitob nomi')),
                ('author', models.CharField(max_length=50, verbose_name='muallifi')),
                ('year', models.DateTimeField(verbose_name='chop etilgan sanasi')),
                ('pages', models.IntegerField(verbose_name='sahifalar soni')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
