# Generated by Django 4.2.11 on 2024-05-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='kitob rasmi'),
        ),
    ]
